monolog:
    channels: ['api', 'auth', 'audit']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        api:
            type: stream
            path: '%kernel.logs_dir%/api.log'
            level: info
            channels: ['api']
        auth:
            type: stream
            path: '%kernel.logs_dir%/auth.log'
            level: info
            channels: ['auth']
