-- Baseline tables for initial domain model (Oracle syntax)
CREATE TABLE carte_visa (
    id_carte NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_carte VARCHAR2(40 CHAR) NOT NULL UNIQUE,
    date_expiration DATE NOT NULL,
    statut NUMBER(1,0) DEFAULT 1 NOT NULL,
    plafond_journalier NUMBER(19,2) NOT NULL,
    id_compte NUMBER(19,0) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE utilisateur_role (
    id_user NUMBER(19,0) NOT NULL,
    id_role NUMBER(19,0) NOT NULL,
    PRIMARY KEY (id_user, id_role)
);
