-- V0: Initial core database schema
-- Crée toutes les tables de base avec leurs noms originaux (sans préfixe soutra_)
-- afin que V8 (rename to soutra_) puisse les renommer.
-- Les tables ajoutées après V8 sont créées directement avec le préfixe soutra_.
-- Idempotent: chaque CREATE TABLE est encapsulé dans un bloc BEGIN-EXCEPTION-END
-- qui ignore ORA-00955 (name is already used by an existing object).

-- ============================================================================
-- 1. TABLES SANS DÉPENDANCES FK (lookups, autonomes)
-- ============================================================================

-- 1.1 agence
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE agence (
            id_agence NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_agence VARCHAR2(20 CHAR) NOT NULL,
            nom VARCHAR2(150 CHAR) NOT NULL,
            adresse VARCHAR2(255 CHAR),
            telephone VARCHAR2(30 CHAR),
            est_active NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_agence PRIMARY KEY (id_agence),
            CONSTRAINT uk_agence_code UNIQUE (code_agence)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.2 statut_client
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE statut_client (
            id_statut_client NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            libelle_statut VARCHAR2(100 CHAR) NOT NULL,
            date_statut TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_statut_client PRIMARY KEY (id_statut_client)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.3 statut_credit
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE statut_credit (
            id_statut_credit NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_statut VARCHAR2(50 CHAR) NOT NULL,
            libelle VARCHAR2(100 CHAR) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_statut_credit PRIMARY KEY (id_statut_credit),
            CONSTRAINT uk_statut_credit_code UNIQUE (code_statut)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.4 type_compte
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE type_compte (
            id_type_compte NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            libelle VARCHAR2(100 CHAR) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_type_compte PRIMARY KEY (id_type_compte)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.5 type_transaction
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE type_transaction (
            id_type_transaction NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_type_transaction VARCHAR2(50 CHAR) NOT NULL,
            libelle VARCHAR2(100 CHAR) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_type_transaction PRIMARY KEY (id_type_transaction),
            CONSTRAINT uk_type_transaction_code UNIQUE (code_type_transaction)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.6 type_agio
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE type_agio (
            id_type_agio NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_type_agio VARCHAR2(50 CHAR) NOT NULL,
            libelle VARCHAR2(100 CHAR) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_type_agio PRIMARY KEY (id_type_agio),
            CONSTRAINT uk_type_agio_code UNIQUE (code_type_agio)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.7 type_canal
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE type_canal (
            id_canal NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_canal VARCHAR2(50 CHAR) NOT NULL,
            libelle VARCHAR2(100 CHAR) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_type_canal PRIMARY KEY (id_canal),
            CONSTRAINT uk_type_canal_code UNIQUE (code_canal)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.8 statut_envoi
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE statut_envoi (
            id_statut_envoi NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_statut_envoi VARCHAR2(50 CHAR) NOT NULL,
            libelle VARCHAR2(100 CHAR) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_statut_envoi PRIMARY KEY (id_statut_envoi),
            CONSTRAINT uk_statut_envoi_code UNIQUE (code_statut_envoi)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.9 role_utilisateur
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE role_utilisateur (
            id_role NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_role_utilisateur VARCHAR2(50 CHAR) NOT NULL,
            intitule_role VARCHAR2(100 CHAR) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_role_utilisateur PRIMARY KEY (id_role),
            CONSTRAINT uk_role_utilisateur_code UNIQUE (code_role_utilisateur)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.10 produit_credit
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE produit_credit (
            id_produit_credit NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_produit VARCHAR2(50 CHAR) NOT NULL,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            taux_interet_annuel NUMBER(7,4) NOT NULL,
            duree_min_mois NUMBER(10,0) NOT NULL,
            duree_max_mois NUMBER(10,0) NOT NULL,
            montant_min NUMBER(19,2) NOT NULL,
            montant_max NUMBER(19,2) NOT NULL,
            methode_calcul VARCHAR2(20 CHAR) NOT NULL,
            frais_dossier_pourcentage NUMBER(7,4),
            penalite_retard_pourcentage NUMBER(7,4),
            est_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_produit_credit PRIMARY KEY (id_produit_credit),
            CONSTRAINT uk_produit_credit_code UNIQUE (code_produit)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.11 produit_epargne
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE produit_epargne (
            id_produit_epargne NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_produit VARCHAR2(50 CHAR) NOT NULL,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            taux_interet_annuel NUMBER(7,4) NOT NULL,
            montant_min_ouverture NUMBER(19,2),
            penalite_retrait_anticipe NUMBER(7,4),
            duree_min_jours NUMBER(10,0),
            est_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_produit_epargne PRIMARY KEY (id_produit_epargne),
            CONSTRAINT uk_produit_epargne_code UNIQUE (code_produit)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 1.12 system_audit_log (ne dépend d'aucune table)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE system_audit_log (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            date_action TIMESTAMP NOT NULL,
            utilisateur VARCHAR2(100 CHAR) NOT NULL,
            action VARCHAR2(100 CHAR) NOT NULL,
            ressource VARCHAR2(100 CHAR),
            adresse_ip VARCHAR2(45 CHAR),
            methode VARCHAR2(255 CHAR),
            statut VARCHAR2(20 CHAR) NOT NULL,
            message_erreur VARCHAR2(500 CHAR),
            CONSTRAINT pk_system_audit_log PRIMARY KEY (id)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ============================================================================
-- 2. TABLES AVEC FK VERS 1.
-- ============================================================================

-- 2.1 client (FK -> statut_client, agence)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE client (
            id_client NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            code_client VARCHAR2(50 CHAR) NOT NULL,
            nom VARCHAR2(100 CHAR) NOT NULL,
            prenom VARCHAR2(100 CHAR) NOT NULL,
            date_naissance DATE,
            adresse VARCHAR2(255 CHAR),
            telephone VARCHAR2(30 CHAR),
            email VARCHAR2(150 CHAR),
            type_piece_identite VARCHAR2(30 CHAR),
            numero_piece_identite VARCHAR2(80 CHAR),
            date_expiration_piece_identite DATE,
            photo_identite_url VARCHAR2(255 CHAR),
            justificatif_domicile_url VARCHAR2(255 CHAR),
            justificatif_revenus_url VARCHAR2(255 CHAR),
            profession VARCHAR2(120 CHAR),
            employeur VARCHAR2(150 CHAR),
            pays_nationalite VARCHAR2(80 CHAR),
            pays_residence VARCHAR2(80 CHAR),
            pep NUMBER(1,0) DEFAULT 0 NOT NULL,
            niveau_risque VARCHAR2(20 CHAR) DEFAULT 'FAIBLE' NOT NULL,
            statut_kyc VARCHAR2(30 CHAR) DEFAULT 'BROUILLON' NOT NULL,
            date_soumission_kyc DATE,
            date_validation_kyc DATE,
            commentaire_kyc VARCHAR2(500 CHAR),
            validateur_kyc VARCHAR2(120 CHAR),
            date_inscription DATE NOT NULL,
            revenu_mensuel NUMBER(19,2),
            secteur_activite VARCHAR2(100 CHAR),
            id_statut_client NUMBER(19,0) NOT NULL,
            id_agence NUMBER(19,0),
            version NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_client PRIMARY KEY (id_client),
            CONSTRAINT uk_client_code UNIQUE (code_client),
            CONSTRAINT uk_client_telephone UNIQUE (telephone),
            CONSTRAINT uk_client_email UNIQUE (email),
            CONSTRAINT uk_client_num_piece_identite UNIQUE (numero_piece_identite),
            CONSTRAINT fk_client_statut FOREIGN KEY (id_statut_client) REFERENCES statut_client(id_statut_client),
            CONSTRAINT fk_client_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.2 utilisateur (FK -> client, agence)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE utilisateur (
            id_user NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            login VARCHAR2(100 CHAR) NOT NULL,
            password VARCHAR2(255 CHAR) NOT NULL,
            actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            compte_expire_le TIMESTAMP,
            compte_verrouille_jusqu_au TIMESTAMP,
            nombre_echecs_connexion NUMBER(10,0) DEFAULT 0 NOT NULL,
            dernier_echec_connexion TIMESTAMP,
            derniere_connexion_reussie TIMESTAMP,
            mot_de_passe_modifie_le TIMESTAMP NOT NULL,
            identifiants_expirent_le TIMESTAMP NOT NULL,
            second_facteur_active NUMBER(1,0) DEFAULT 1 NOT NULL,
            otp_challenge_id VARCHAR2(80 CHAR),
            otp_hash VARCHAR2(255 CHAR),
            otp_expire_le TIMESTAMP,
            otp_tentatives_restantes NUMBER(10,0) DEFAULT 0 NOT NULL,
            reset_token_hash VARCHAR2(255 CHAR),
            reset_token_expire_le TIMESTAMP,
            last_password_change TIMESTAMP,
            id_client NUMBER(19,0) NOT NULL,
            id_agence NUMBER(19,0),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_utilisateur PRIMARY KEY (id_user),
            CONSTRAINT uk_utilisateur_login UNIQUE (login),
            CONSTRAINT uk_utilisateur_id_client UNIQUE (id_client),
            CONSTRAINT fk_utilisateur_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_utilisateur_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.3 compte (FK -> client, type_compte, agence, produit_epargne)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE compte (
            id_compte NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            num_compte VARCHAR2(50 CHAR) NOT NULL,
            solde NUMBER(19,2) NOT NULL,
            date_ouverture DATE NOT NULL,
            devise VARCHAR2(10 CHAR) NOT NULL,
            taux_interet NUMBER(7,4),
            decouvert_autorise NUMBER(19,2),
            id_client NUMBER(19,0) NOT NULL,
            id_type_compte NUMBER(19,0) NOT NULL,
            id_agence NUMBER(19,0),
            id_produit_epargne NUMBER(19,0),
            version NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_compte PRIMARY KEY (id_compte),
            CONSTRAINT uk_compte_num UNIQUE (num_compte),
            CONSTRAINT fk_compte_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_compte_type FOREIGN KEY (id_type_compte) REFERENCES type_compte(id_type_compte),
            CONSTRAINT fk_compte_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence),
            CONSTRAINT fk_compte_produit_epargne FOREIGN KEY (id_produit_epargne) REFERENCES produit_epargne(id_produit_epargne)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.4 statut_compte (FK -> compte)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE statut_compte (
            id_statut_compte NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            libelle_statut VARCHAR2(100 CHAR) NOT NULL,
            date_statut TIMESTAMP NOT NULL,
            id_compte NUMBER(19,0) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_statut_compte PRIMARY KEY (id_statut_compte),
            CONSTRAINT fk_statut_compte_compte FOREIGN KEY (id_compte) REFERENCES compte(id_compte)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.5 demande_credit (FK -> client, produit_credit, utilisateur)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE demande_credit (
            id_demande NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference_demande VARCHAR2(80 CHAR) NOT NULL,
            montant_demande NUMBER(19,2) NOT NULL,
            duree_souhaitee NUMBER(10,0) NOT NULL,
            objet_credit VARCHAR2(500 CHAR) NOT NULL,
            date_demande DATE NOT NULL,
            date_decision TIMESTAMP,
            motif_rejet VARCHAR2(500 CHAR),
            score_client NUMBER(10,0),
            statut_demande VARCHAR2(20 CHAR) NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            id_produit_credit NUMBER(19,0) NOT NULL,
            id_agent_credit NUMBER(19,0),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_demande_credit PRIMARY KEY (id_demande),
            CONSTRAINT uk_demande_credit_ref UNIQUE (reference_demande),
            CONSTRAINT fk_demande_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_demande_produit FOREIGN KEY (id_produit_credit) REFERENCES produit_credit(id_produit_credit),
            CONSTRAINT fk_demande_agent FOREIGN KEY (id_agent_credit) REFERENCES utilisateur(id_user)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.6 bank_transaction (FK -> utilisateur, type_transaction, compte)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE bank_transaction (
            id_transaction NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference_unique VARCHAR2(80 CHAR) NOT NULL,
            date_heure_transaction TIMESTAMP NOT NULL,
            montant_global NUMBER(19,2) NOT NULL,
            frais NUMBER(19,2) NOT NULL,
            statut_operation VARCHAR2(30 CHAR) DEFAULT 'EN_ATTENTE' NOT NULL,
            validation_superviseur_requise NUMBER(1,0) DEFAULT 0 NOT NULL,
            date_validation TIMESTAMP,
            date_execution TIMESTAMP,
            motif_rejet VARCHAR2(500 CHAR),
            id_user NUMBER(19,0) NOT NULL,
            id_user_validation NUMBER(19,0),
            id_type_transaction NUMBER(19,0) NOT NULL,
            id_compte_source NUMBER(19,0),
            id_compte_destination NUMBER(19,0),
            version NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_bank_transaction PRIMARY KEY (id_transaction),
            CONSTRAINT uk_bank_transaction_ref UNIQUE (reference_unique),
            CONSTRAINT fk_transaction_user FOREIGN KEY (id_user) REFERENCES utilisateur(id_user),
            CONSTRAINT fk_transaction_user_val FOREIGN KEY (id_user_validation) REFERENCES utilisateur(id_user),
            CONSTRAINT fk_transaction_type FOREIGN KEY (id_type_transaction) REFERENCES type_transaction(id_type_transaction),
            CONSTRAINT fk_transaction_cpte_src FOREIGN KEY (id_compte_source) REFERENCES compte(id_compte),
            CONSTRAINT fk_transaction_cpte_dst FOREIGN KEY (id_compte_destination) REFERENCES compte(id_compte)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.7 caisse (FK -> utilisateur)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE caisse (
            id_caisse NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_user NUMBER(19,0) NOT NULL,
            solde_ouverture NUMBER(19,2) NOT NULL,
            solde_courant NUMBER(19,2) NOT NULL,
            statut VARCHAR2(20 CHAR) NOT NULL,
            date_ouverture TIMESTAMP NOT NULL,
            date_fermeture TIMESTAMP,
            ecart_fermeture NUMBER(19,2),
            version NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_caisse PRIMARY KEY (id_caisse),
            CONSTRAINT fk_caisse_user FOREIGN KEY (id_user) REFERENCES utilisateur(id_user)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.8 credit (FK -> client, produit_credit, statut_credit, compte, demande_credit)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE credit (
            id_credit NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference_credit VARCHAR2(80 CHAR) NOT NULL,
            montant_accorde NUMBER(19,2) NOT NULL,
            montant_restant_du NUMBER(19,2) NOT NULL,
            taux_interet_annuel NUMBER(7,4) NOT NULL,
            duree_mois NUMBER(10,0) NOT NULL,
            methode_calcul VARCHAR2(20 CHAR) NOT NULL,
            frais_dossier NUMBER(19,2),
            date_decaissement DATE,
            date_fin_prevue DATE,
            id_client NUMBER(19,0) NOT NULL,
            id_produit_credit NUMBER(19,0) NOT NULL,
            id_statut_credit NUMBER(19,0) NOT NULL,
            id_compte_decaissement NUMBER(19,0),
            id_demande NUMBER(19,0),
            version NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_credit PRIMARY KEY (id_credit),
            CONSTRAINT uk_credit_ref UNIQUE (reference_credit),
            CONSTRAINT uk_credit_demande UNIQUE (id_demande),
            CONSTRAINT fk_credit_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_credit_produit FOREIGN KEY (id_produit_credit) REFERENCES produit_credit(id_produit_credit),
            CONSTRAINT fk_credit_statut FOREIGN KEY (id_statut_credit) REFERENCES statut_credit(id_statut_credit),
            CONSTRAINT fk_credit_cpte_dec FOREIGN KEY (id_compte_decaissement) REFERENCES compte(id_compte),
            CONSTRAINT fk_credit_demande FOREIGN KEY (id_demande) REFERENCES demande_credit(id_demande)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.9 carte_visa (FK -> compte)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE carte_visa (
            id_carte NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            numero_carte VARCHAR2(40 CHAR) NOT NULL,
            date_expiration DATE NOT NULL,
            statut NUMBER(1,0) NOT NULL,
            plafond_journalier NUMBER(19,2) NOT NULL,
            id_compte NUMBER(19,0) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_carte_visa PRIMARY KEY (id_carte),
            CONSTRAINT uk_carte_visa_num UNIQUE (numero_carte),
            CONSTRAINT fk_carte_visa_compte FOREIGN KEY (id_compte) REFERENCES compte(id_compte)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.10 ligne_ecriture (FK -> bank_transaction, compte)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE ligne_ecriture (
            id_ligne NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            sens VARCHAR2(20 CHAR) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            id_transaction NUMBER(19,0) NOT NULL,
            id_compte NUMBER(19,0) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_ligne_ecriture PRIMARY KEY (id_ligne),
            CONSTRAINT fk_ligne_transaction FOREIGN KEY (id_transaction) REFERENCES bank_transaction(id_transaction),
            CONSTRAINT fk_ligne_compte FOREIGN KEY (id_compte) REFERENCES compte(id_compte)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.11 echeance (FK -> credit)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE echeance (
            id_echeance NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            numero_echeance NUMBER(10,0) NOT NULL,
            date_echeance DATE NOT NULL,
            montant_capital NUMBER(19,2) NOT NULL,
            montant_interet NUMBER(19,2) NOT NULL,
            montant_total NUMBER(19,2) NOT NULL,
            montant_penalite NUMBER(19,2),
            montant_paye NUMBER(19,2) NOT NULL,
            date_paiement DATE,
            est_payee NUMBER(1,0) NOT NULL,
            id_credit NUMBER(19,0) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_echeance PRIMARY KEY (id_echeance),
            CONSTRAINT fk_echeance_credit FOREIGN KEY (id_credit) REFERENCES credit(id_credit)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.12 garantie (FK -> credit)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE garantie (
            id_garantie NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            type_garantie VARCHAR2(30 CHAR) NOT NULL,
            description VARCHAR2(500 CHAR) NOT NULL,
            valeur_estimee NUMBER(19,2),
            est_active NUMBER(1,0) DEFAULT 1 NOT NULL,
            id_credit NUMBER(19,0) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_garantie PRIMARY KEY (id_garantie),
            CONSTRAINT fk_garantie_credit FOREIGN KEY (id_credit) REFERENCES credit(id_credit)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.13 notification (FK -> type_canal, statut_envoi, client)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE notification (
            id_notif NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            message VARCHAR2(500 CHAR) NOT NULL,
            date_envoi DATE,
            erreur_envoi VARCHAR2(500 CHAR),
            id_canal NUMBER(19,0) NOT NULL,
            id_statut_envoi NUMBER(19,0) NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            lu NUMBER(1,0) DEFAULT 0 NOT NULL,
            lue_le TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_notification PRIMARY KEY (id_notif),
            CONSTRAINT fk_notif_canal FOREIGN KEY (id_canal) REFERENCES type_canal(id_canal),
            CONSTRAINT fk_notif_statut FOREIGN KEY (id_statut_envoi) REFERENCES statut_envoi(id_statut_envoi),
            CONSTRAINT fk_notif_client FOREIGN KEY (id_client) REFERENCES client(id_client)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2.14 agio (FK -> compte, type_agio)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE agio (
            id_agio NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            date_calcul DATE NOT NULL,
            est_preleve NUMBER(1,0) NOT NULL,
            id_compte NUMBER(19,0) NOT NULL,
            id_type_agio NUMBER(19,0) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_agio PRIMARY KEY (id_agio),
            CONSTRAINT fk_agio_compte FOREIGN KEY (id_compte) REFERENCES compte(id_compte),
            CONSTRAINT fk_agio_type FOREIGN KEY (id_type_agio) REFERENCES type_agio(id_type_agio)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ============================================================================
-- 3. JOINTURE MANY-TO-MANY
-- ============================================================================

-- 3.1 utilisateur_role (FK -> utilisateur, role_utilisateur)
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE utilisateur_role (
            id_user NUMBER(19,0) NOT NULL,
            id_role NUMBER(19,0) NOT NULL,
            CONSTRAINT pk_utilisateur_role PRIMARY KEY (id_user, id_role),
            CONSTRAINT fk_ur_user FOREIGN KEY (id_user) REFERENCES utilisateur(id_user),
            CONSTRAINT fk_ur_role FOREIGN KEY (id_role) REFERENCES role_utilisateur(id_role)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ============================================================================
-- 4. TABLES CRÉÉES DIRECTEMENT AVEC PRÉFIXE SOUTRA_ (POST-V8)
-- ============================================================================

-- 4.1 soutra_beneficiaire
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_beneficiaire (
            id_beneficiaire NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            nom VARCHAR2(100 CHAR) NOT NULL,
            prenom VARCHAR2(100 CHAR),
            compte_beneficiaire VARCHAR2(50 CHAR) NOT NULL,
            banque VARCHAR2(100 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_beneficiaire PRIMARY KEY (id_beneficiaire)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4.2 soutra_document_client
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_document_client (
            id_doc NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            nom_fichier VARCHAR2(255 CHAR) NOT NULL,
            type_mime VARCHAR2(100 CHAR) NOT NULL,
            taille_octets NUMBER(19,0) NOT NULL,
            chemin_stockage VARCHAR2(500 CHAR) NOT NULL,
            categorie VARCHAR2(50 CHAR),
            uploaded_by NUMBER(19,0),
            date_upload TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_document_client PRIMARY KEY (id_doc)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4.3 soutra_notification_preference
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_notification_preference (
            id_pref NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            push_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            sms_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            email_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_notif_pref PRIMARY KEY (id_pref),
            CONSTRAINT uk_soutra_notif_pref_client UNIQUE (id_client)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
