BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE parametre_agence (
            id_parametre_agence NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_agence NUMBER(19,0) NOT NULL,
            code_parametre VARCHAR2(80 CHAR) NOT NULL,
            valeur_parametre VARCHAR2(500 CHAR) NOT NULL,
            type_valeur VARCHAR2(30 CHAR) DEFAULT ''STRING'' NOT NULL,
            description_parametre VARCHAR2(255 CHAR),
            date_effet DATE NOT NULL,
            date_fin DATE,
            actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            version_parametre NUMBER(10,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_parametre_agence_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence),
            CONSTRAINT uk_parametre_agence_version UNIQUE (id_agence, code_parametre, version_parametre),
            CONSTRAINT ck_parametre_agence_dates CHECK (date_fin IS NULL OR date_fin >= date_effet)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE mutation_personnel (
            id_mutation_personnel NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_employe NUMBER(19,0) NOT NULL,
            id_agence_source NUMBER(19,0) NOT NULL,
            id_agence_destination NUMBER(19,0) NOT NULL,
            date_mutation DATE NOT NULL,
            motif VARCHAR2(500 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''INITIEE'' NOT NULL,
            id_validateur NUMBER(19,0),
            date_validation TIMESTAMP,
            commentaire_validation VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_mutation_employe FOREIGN KEY (id_employe) REFERENCES employe(id_employe),
            CONSTRAINT fk_mutation_agence_source FOREIGN KEY (id_agence_source) REFERENCES agence(id_agence),
            CONSTRAINT fk_mutation_agence_destination FOREIGN KEY (id_agence_destination) REFERENCES agence(id_agence),
            CONSTRAINT fk_mutation_validateur FOREIGN KEY (id_validateur) REFERENCES utilisateur(id_user),
            CONSTRAINT ck_mutation_agences_diff CHECK (id_agence_source <> id_agence_destination)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE compte_liaison_agence (
            id_compte_liaison_agence NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_agence_source NUMBER(19,0) NOT NULL,
            id_agence_destination NUMBER(19,0) NOT NULL,
            id_compte_comptable NUMBER(19,0) NOT NULL,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_compte_liaison_source FOREIGN KEY (id_agence_source) REFERENCES agence(id_agence),
            CONSTRAINT fk_compte_liaison_destination FOREIGN KEY (id_agence_destination) REFERENCES agence(id_agence),
            CONSTRAINT fk_compte_liaison_compte FOREIGN KEY (id_compte_comptable) REFERENCES compte_comptable(id_compte_comptable),
            CONSTRAINT uk_compte_liaison_unique UNIQUE (id_agence_source, id_agence_destination, id_compte_comptable),
            CONSTRAINT ck_compte_liaison_agences_diff CHECK (id_agence_source <> id_agence_destination)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE operation_deplacee (
            id_operation_deplacee NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_transaction NUMBER(19,0) NOT NULL,
            id_agence_origine NUMBER(19,0) NOT NULL,
            id_agence_operante NUMBER(19,0) NOT NULL,
            type_operation VARCHAR2(40 CHAR) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            devise VARCHAR2(10 CHAR) DEFAULT ''XOF'' NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''INITIEE'' NOT NULL,
            reference_operation VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            date_operation TIMESTAMP NOT NULL,
            commentaire VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_operation_deplacee_transaction FOREIGN KEY (id_transaction) REFERENCES bank_transaction(id_transaction),
            CONSTRAINT fk_operation_deplacee_origine FOREIGN KEY (id_agence_origine) REFERENCES agence(id_agence),
            CONSTRAINT fk_operation_deplacee_operante FOREIGN KEY (id_agence_operante) REFERENCES agence(id_agence),
            CONSTRAINT uk_operation_deplacee_transaction UNIQUE (id_transaction),
            CONSTRAINT ck_operation_deplacee_agences_diff CHECK (id_agence_origine <> id_agence_operante)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE commission_inter_agence (
            id_commission_inter_agence NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_operation_deplacee NUMBER(19,0) NOT NULL,
            taux_commission NUMBER(9,4) DEFAULT 0 NOT NULL,
            montant_commission NUMBER(19,2) DEFAULT 0 NOT NULL,
            id_compte_comptable NUMBER(19,0),
            statut VARCHAR2(30 CHAR) DEFAULT ''CALCULEE'' NOT NULL,
            reference_piece VARCHAR2(80 CHAR),
            date_calcul TIMESTAMP NOT NULL,
            date_comptabilisation TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_commission_operation FOREIGN KEY (id_operation_deplacee) REFERENCES operation_deplacee(id_operation_deplacee),
            CONSTRAINT fk_commission_compte FOREIGN KEY (id_compte_comptable) REFERENCES compte_comptable(id_compte_comptable),
            CONSTRAINT uk_commission_operation UNIQUE (id_operation_deplacee)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE rapprochement_inter_agence (
            id_rapprochement_inter_agence NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_agence_source NUMBER(19,0) NOT NULL,
            id_agence_destination NUMBER(19,0) NOT NULL,
            periode_debut DATE NOT NULL,
            periode_fin DATE NOT NULL,
            date_rapprochement TIMESTAMP NOT NULL,
            montant_debit NUMBER(19,2) DEFAULT 0 NOT NULL,
            montant_credit NUMBER(19,2) DEFAULT 0 NOT NULL,
            ecart NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''BROUILLON'' NOT NULL,
            id_validateur NUMBER(19,0),
            commentaire VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_rapprochement_source FOREIGN KEY (id_agence_source) REFERENCES agence(id_agence),
            CONSTRAINT fk_rapprochement_destination FOREIGN KEY (id_agence_destination) REFERENCES agence(id_agence),
            CONSTRAINT fk_rapprochement_validateur FOREIGN KEY (id_validateur) REFERENCES utilisateur(id_user),
            CONSTRAINT ck_rapprochement_agences_diff CHECK (id_agence_source <> id_agence_destination),
            CONSTRAINT ck_rapprochement_periode CHECK (periode_fin >= periode_debut)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_parametre_agence_scope ON parametre_agence (id_agence, code_parametre, actif)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_mutation_personnel_employe ON mutation_personnel (id_employe, date_mutation)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_operation_deplacee_agence ON operation_deplacee (id_agence_operante, date_operation)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_rapprochement_inter_agence ON rapprochement_inter_agence (id_agence_source, id_agence_destination, date_rapprochement)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
