-- V10: Create Conformite (Compliance) tables for SOUTRA Microfinance
-- Conformite reglementaire BCEAO/COBAC: SARSCENTIF, Reclamations, RGPD, PEP, LCB-FT

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_rapport_sars_centif (
            id_rapport NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference VARCHAR2(50) NOT NULL,
            id_client NUMBER,
            type_alerte VARCHAR2(100) NOT NULL,
            description CLOB,
            montant_soupconne NUMBER(19,2),
            statut VARCHAR2(30) DEFAULT 'NOUVEAU' NOT NULL,
            date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            date_traitement TIMESTAMP,
            soumis_par VARCHAR2(100),
            traite_par VARCHAR2(100),
            motif_rejet CLOB,
            transmission_centif NUMBER(1) DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_rapport_sars_centif PRIMARY KEY (id_rapport),
            CONSTRAINT uk_rapport_sars_centif_ref UNIQUE (reference)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE soutra_rapport_sars_centif IS 'Rapports SARSCENTIF (Declarations Operations Suspectes) - Conformite BCEAO/COBAC';
COMMENT ON COLUMN soutra_rapport_sars_centif.id_rapport IS 'Identifiant unique du rapport';
COMMENT ON COLUMN soutra_rapport_sars_centif.reference IS 'Reference unique du rapport';
COMMENT ON COLUMN soutra_rapport_sars_centif.id_client IS 'Reference vers le client concerne (soutra_client.id_client)';
COMMENT ON COLUMN soutra_rapport_sars_centif.type_alerte IS 'Type d''alerte (ex: FRAUDE, BLANCHIMENT, FINANCEMENT_TERRORISME)';
COMMENT ON COLUMN soutra_rapport_sars_centif.description IS 'Description detaillee de l''operation suspecte';
COMMENT ON COLUMN soutra_rapport_sars_centif.montant_soupconne IS 'Montant soupconne de l''operation';
COMMENT ON COLUMN soutra_rapport_sars_centif.statut IS 'Statut du rapport (NOUVEAU, TRANSMIS, CLOTURE, REJETE)';
COMMENT ON COLUMN soutra_rapport_sars_centif.transmission_centif IS 'Indique si le rapport a ete transmis a CENTIF (0=Non, 1=Oui)';

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_rapport_sars_statut ON soutra_rapport_sars_centif(statut)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_rapport_sars_client ON soutra_rapport_sars_centif(id_client)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_reclamation (
            id_reclamation NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference VARCHAR2(50) NOT NULL,
            id_client NUMBER,
            type_reclamation VARCHAR2(100) NOT NULL,
            description CLOB,
            statut VARCHAR2(30) DEFAULT 'NOUVEAU' NOT NULL,
            priorite VARCHAR2(20) DEFAULT 'NORMALE',
            date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            date_traitement TIMESTAMP,
            cree_par VARCHAR2(100),
            traite_par VARCHAR2(100),
            motif_cloture CLOB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_reclamation PRIMARY KEY (id_reclamation),
            CONSTRAINT uk_reclamation_ref UNIQUE (reference)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE soutra_reclamation IS 'Reclamations clients - Gestion des plaintes et differents';
COMMENT ON COLUMN soutra_reclamation.id_reclamation IS 'Identifiant unique de la reclamation';
COMMENT ON COLUMN soutra_reclamation.reference IS 'Reference unique de la reclamation';
COMMENT ON COLUMN soutra_reclamation.id_client IS 'Reference vers le client plaignant (soutra_client.id_client)';
COMMENT ON COLUMN soutra_reclamation.type_reclamation IS 'Type de reclamation (ex: FRAUDE, ERREUR_ADMIN, SERVICE_CLIENT)';
COMMENT ON COLUMN soutra_reclamation.priorite IS 'Priorite (BASSE, NORMALE, HAUTE, CRITIQUE)';

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_reclamation_statut ON soutra_reclamation(statut)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_reclamation_client ON soutra_reclamation(id_client)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_consentement_rgpd (
            id_consentement NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER,
            finalite VARCHAR2(200) NOT NULL,
            consenti NUMBER(1) DEFAULT 0,
            date_consentement TIMESTAMP,
            date_expiration TIMESTAMP,
            adresse_ip VARCHAR2(50),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_consentement_rgpd PRIMARY KEY (id_consentement)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE soutra_consentement_rgpd IS 'Consentements RGPD des clients - Protection des donnees personnelles';
COMMENT ON COLUMN soutra_consentement_rgpd.id_client IS 'Reference vers le client (soutra_client.id_client)';
COMMENT ON COLUMN soutra_consentement_rgpd.finalite IS 'Finalite du traitement (ex: COMMUNICATION_COMMERCIALE, PARTAGE_TIERS)';
COMMENT ON COLUMN soutra_consentement_rgpd.consenti IS 'Indique si le consentement a ete donne (0=Non, 1=Oui)';
COMMENT ON COLUMN soutra_consentement_rgpd.date_expiration IS 'Date d''expiration du consentement (si applicable)';

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_consentement_client ON soutra_consentement_rgpd(id_client)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_pep (
            id_pep NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER,
            nom_complet VARCHAR2(200) NOT NULL,
            fonction VARCHAR2(200),
            pays VARCHAR2(100),
            niveau_risque VARCHAR2(20) DEFAULT 'FAIBLE',
            date_declaration TIMESTAMP NOT NULL,
            source_information VARCHAR2(200),
            verifie_par VARCHAR2(100),
            date_verification TIMESTAMP,
            statut VARCHAR2(20) DEFAULT 'ACTIF' NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_pep PRIMARY KEY (id_pep)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE soutra_pep IS 'Personnes Politiquement Exposees (PPE/PEP) - Conformite LCB-FT';
COMMENT ON COLUMN soutra_pep.id_client IS 'Reference vers le client declare (soutra_client.id_client)';
COMMENT ON COLUMN soutra_pep.nom_complet IS 'Nom complet de la personne politiquement exposee';
COMMENT ON COLUMN soutra_pep.fonction IS 'Fonction politique ou publique occupee';
COMMENT ON COLUMN soutra_pep.niveau_risque IS 'Niveau de risque attribue (FAIBLE, MOYEN, ELEVE, CRITIQUE)';
COMMENT ON COLUMN soutra_pep.date_declaration IS 'Date de declaration de la personne';
COMMENT ON COLUMN soutra_pep.source_information IS 'Source des informations de la declaration';

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_pep_client ON soutra_pep(id_client)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_pep_statut ON soutra_pep(statut)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_alerte_lcbft (
            id_alerte NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER,
            type_alerte VARCHAR2(100) NOT NULL,
            description CLOB,
            niveau_risque VARCHAR2(20) NOT NULL,
            statut VARCHAR2(20) DEFAULT 'OUVERTE' NOT NULL,
            date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            date_traitement TIMESTAMP,
            traite_par VARCHAR2(100),
            actions CLOB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_alerte_lcbft PRIMARY KEY (id_alerte)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE soutra_alerte_lcbft IS 'Alertes LCB-FT (Lutte Contre le Blanchiment et le Financement du Terrorisme)';
COMMENT ON COLUMN soutra_alerte_lcbft.id_client IS 'Reference vers le client concerne (soutra_client.id_client)';
COMMENT ON COLUMN soutra_alerte_lcbft.type_alerte IS 'Type d''alerte (ex: TRANSACTION_INHABITUELLE, VOLUME_ELEVE, P EP)';
COMMENT ON COLUMN soutra_alerte_lcbft.niveau_risque IS 'Niveau de risque (FAIBLE, MOYEN, ELEVE, CRITIQUE)';
COMMENT ON COLUMN soutra_alerte_lcbft.actions IS 'Actions correctrices entreprises';

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_alerte_lcbft_statut ON soutra_alerte_lcbft(statut)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_alerte_lcbft_risque ON soutra_alerte_lcbft(niveau_risque)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_alerte_lcbft_client ON soutra_alerte_lcbft(id_client)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
