-- V11: Create System Audit Log Table for the Audit Trail Module

CREATE TABLE system_audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR2(100) NOT NULL,
    ip_address VARCHAR2(50),
    action VARCHAR2(100) NOT NULL,
    resource_name VARCHAR2(255),
    status VARCHAR2(20) NOT NULL,
    error_details CLOB,
    event_timestamp TIMESTAMP NOT NULL
);

-- Create indexes for common query patterns in audit logs
CREATE INDEX idx_system_audit_log_user ON system_audit_log(user_name);
CREATE INDEX idx_system_audit_log_action ON system_audit_log(action);
CREATE INDEX idx_system_audit_log_status ON system_audit_log(status);
CREATE INDEX idx_system_audit_log_timestamp ON system_audit_log(event_timestamp);
