-- V11: Create Exception/Derogation workflow tables for SOUTRA Microfinance
-- Derogations et Escalades pour les workflows d'approbation (4-yeux, superviseur)

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_derogation (
            id_derogation NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference VARCHAR2(50),
            type_derogation VARCHAR2(50) NOT NULL,
            description VARCHAR2(500) NOT NULL,
            motif VARCHAR2(500) NOT NULL,
            montant_concerne NUMBER(15,2),
            id_client NUMBER,
            id_transaction NUMBER,
            statut VARCHAR2(30) DEFAULT 'SOUMISE' NOT NULL,
            date_creation TIMESTAMP,
            date_traitement TIMESTAMP,
            cree_par VARCHAR2(100),
            traite_par VARCHAR2(100),
            motif_traitement VARCHAR2(500),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_derogation PRIMARY KEY (id_derogation),
            CONSTRAINT uk_derogation_ref UNIQUE (reference)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE soutra_derogation IS 'Derogations - demandes de deviation aux regles standards (plafonds, conditions)';
COMMENT ON COLUMN soutra_derogation.id_derogation IS 'Identifiant unique de la derogation';
COMMENT ON COLUMN soutra_derogation.reference IS 'Reference unique de la derogation';
COMMENT ON COLUMN soutra_derogation.type_derogation IS 'Type de derogation (ex: PLAFOND_DECAISSEMENT, TAUX_INTERET, FRAIS)';
COMMENT ON COLUMN soutra_derogation.description IS 'Description de la derogation demandee';
COMMENT ON COLUMN soutra_derogation.motif IS 'Motif justifiant la derogation';
COMMENT ON COLUMN soutra_derogation.montant_concerne IS 'Montant concerne par la derogation';
COMMENT ON COLUMN soutra_derogation.id_client IS 'Reference vers le client concerne (soutra_client.id_client)';
COMMENT ON COLUMN soutra_derogation.id_transaction IS 'Reference vers la transaction concernee (soutra_transaction.id)';
COMMENT ON COLUMN soutra_derogation.statut IS 'Statut (SOUMISE, APPROUVE, REJETE, ANNULEE)';
COMMENT ON COLUMN soutra_derogation.motif_traitement IS 'Motif de la decision (approbation ou rejet)';

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_derogation_statut ON soutra_derogation(statut)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_derogation_type ON soutra_derogation(type_derogation)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_escalade (
            id_escalade NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            reference VARCHAR2(50),
            type_escalade VARCHAR2(50) NOT NULL,
            description VARCHAR2(500) NOT NULL,
            niveau VARCHAR2(10) DEFAULT 'N1' NOT NULL,
            statut VARCHAR2(30) DEFAULT 'OUVERTE' NOT NULL,
            id_client NUMBER,
            id_transaction NUMBER,
            date_creation TIMESTAMP,
            date_traitement TIMESTAMP,
            cree_par VARCHAR2(100),
            traite_par VARCHAR2(100),
            action VARCHAR2(50),
            commentaire VARCHAR2(500),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_escalade PRIMARY KEY (id_escalade),
            CONSTRAINT uk_escalade_ref UNIQUE (reference)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE soutra_escalade IS 'Escalades - remontee hierarchique pour decisions non resolubles au niveau courant';
COMMENT ON COLUMN soutra_escalade.id_escalade IS 'Identifiant unique de l''escalade';
COMMENT ON COLUMN soutra_escalade.reference IS 'Reference unique de l''escalade';
COMMENT ON COLUMN soutra_escalade.type_escalade IS 'Type d''escalade (ex: CONFLIT_CLIENT, FRAUDE, DECISION_CREDIT)';
COMMENT ON COLUMN soutra_escalade.niveau IS 'Niveau d''escalade (N1, N2, N3)';
COMMENT ON COLUMN soutra_escalade.statut IS 'Statut (OUVERTE, EN_COURS, RESOLUE, FERMEE)';
COMMENT ON COLUMN soutra_escalade.id_client IS 'Reference vers le client concerne (soutra_client.id_client)';
COMMENT ON COLUMN soutra_escalade.id_transaction IS 'Reference vers la transaction concerne (soutra_transaction.id)';
COMMENT ON COLUMN soutra_escalade.action IS 'Action requise ou effectuee';

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_escalade_statut ON soutra_escalade(statut)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_escalade_niveau ON soutra_escalade(niveau)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
