-- V12: Seed new credit statuses for enhanced credit lifecycle
-- Cree la table soutra_statut_credit si elle n'existe pas (Hibernate la cree normalement,
-- mais Flyway s'execute avant Hibernate, donc on doit la creer ici)
-- Puis ajoute EN_ETUDE, RESTRUCTURE, SOUFFRANCE au referentiel des statuts de credit
-- Utilise MERGE pour garantir l'idempotence (evite les doublons en cas de reexecution)

-- Creer la table si elle n'existe pas (ORA-00955 = name already used by an existing object)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE soutra_statut_credit (
            id_statut_credit NUMBER GENERATED BY DEFAULT AS IDENTITY,
            code_statut VARCHAR2(50) NOT NULL,
            libelle VARCHAR2(100) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_statut_credit PRIMARY KEY (id_statut_credit),
            CONSTRAINT uk_soutra_statut_credit_code UNIQUE (code_statut)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF; -- Ignore if table already exists
END;
/

-- Inserer les nouveaux statuts de credit
MERGE INTO soutra_statut_credit cible
USING (
    SELECT 'EN_ETUDE' AS code_statut, 'En instruction' AS libelle FROM dual
    UNION ALL
    SELECT 'RESTRUCTURE', 'Restructure' FROM dual
    UNION ALL
    SELECT 'SOUFFRANCE', 'En souffrance' FROM dual
) source
ON (cible.code_statut = source.code_statut)
WHEN NOT MATCHED THEN
    INSERT (code_statut, libelle, created_at, updated_at)
    VALUES (source.code_statut, source.libelle, SYSTIMESTAMP, SYSTIMESTAMP);
