DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = 'HISTORIQUE_MOT_DE_PASSE_UTILISATEUR';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE historique_mot_de_passe_utilisateur (
                id_historique_mdp NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_user NUMBER NOT NULL,
                hash_mot_de_passe VARCHAR2(255 CHAR) NOT NULL,
                date_changement TIMESTAMP NOT NULL,
                motif VARCHAR2(255 CHAR),
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )
        ]';

        EXECUTE IMMEDIATE 'CREATE INDEX idx_hist_mdp_user_date ON historique_mot_de_passe_utilisateur (id_user, date_changement DESC)';
    END IF;
END;
/
