-- V14: Align SYSCOHADA accounting table names with the soutra_ prefix convention.

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE transaction_comptable ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1430, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE transaction_comptable ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1430, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ecriture_comptable ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1430, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ecriture_comptable ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1430, -942) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'RENAME compte_comptable TO soutra_compte_comptable';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -4043, -955) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'RENAME transaction_comptable TO soutra_transaction_comptable';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -4043, -955) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'RENAME ecriture_comptable TO soutra_ecriture_comptable';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -4043, -955) THEN RAISE; END IF;
END;
/

