DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = 'PERMISSION_SECURITE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permission_securite (
                id_permission NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code_permission VARCHAR2(100 CHAR) NOT NULL,
                libelle_permission VARCHAR2(150 CHAR) NOT NULL,
                module_code VARCHAR2(60 CHAR) NOT NULL,
                description_permission VARCHAR2(500 CHAR),
                actif NUMBER(1,0) DEFAULT 1 NOT NULL,
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT uk_permission_securite_code UNIQUE (code_permission)
            )
        ]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_permission_module ON permission_securite (module_code, code_permission)';
    END IF;

    SELECT COUNT(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = 'ROLE_PERMISSION_SECURITE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE role_permission_securite (
                id_role NUMBER(19,0) NOT NULL,
                id_permission NUMBER NOT NULL,
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT pk_role_permission_securite PRIMARY KEY (id_role, id_permission),
                CONSTRAINT fk_role_permission_permission FOREIGN KEY (id_permission) REFERENCES permission_securite(id_permission)
            )
        ]';
    END IF;
END;
/

MERGE INTO permission_securite target
USING (
    SELECT 'SECURITY_PERMISSION_VIEW' code_permission, 'Consulter les permissions' libelle_permission, 'SECURITY' module_code, 'Lecture des permissions et affectations' description_permission FROM dual
    UNION ALL
    SELECT 'SECURITY_PERMISSION_MANAGE', 'Gerer les permissions', 'SECURITY', 'Soumission maker des creations, mises a jour et affectations de permissions' FROM dual
    UNION ALL
    SELECT 'SECURITY_AUDIT_VIEW', 'Consulter les traces d audit', 'SECURITY', 'Lecture des journaux d audit enrichis' FROM dual
) source
ON (target.code_permission = source.code_permission)
WHEN NOT MATCHED THEN
    INSERT (code_permission, libelle_permission, module_code, description_permission, actif, created_at, updated_at)
    VALUES (source.code_permission, source.libelle_permission, source.module_code, source.description_permission, 1, SYSTIMESTAMP, SYSTIMESTAMP);
