-- =============================================================================
-- V17 : Indexes manquants sur les tables créées post-V8
--       (annotations @Index des entités JPA non reflétées dans V0_001)
--       + garde-fou pour les bases locales qui avaient appliqué V16 en no-op
--         avec Hibernate ddl-auto=update, puis sont passées en ddl-auto=validate.
-- =============================================================================
-- Entité Beneficiaire : @Index(name = "ix_soutra_beneficiaire_client",
--                               columnList = "id_client")
-- Entité DocumentClient : @Index(name = "idx_doc_client",
--                                columnList = "id_client"),
--                         @Index(name = "idx_doc_date",
--                                columnList = "date_upload")
-- =============================================================================

-- 0.1 Table soutra_beneficiaire
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_beneficiaire (
            id_beneficiaire NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            nom VARCHAR2(100 CHAR) NOT NULL,
            prenom VARCHAR2(100 CHAR),
            compte_beneficiaire VARCHAR2(50 CHAR) NOT NULL,
            banque VARCHAR2(100 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_beneficiaire PRIMARY KEY (id_beneficiaire)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 0.2 Table soutra_document_client
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_document_client (
            id_doc NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            nom_fichier VARCHAR2(255 CHAR) NOT NULL,
            type_mime VARCHAR2(100 CHAR) NOT NULL,
            taille_octets NUMBER(19,0) NOT NULL,
            chemin_stockage VARCHAR2(500 CHAR) NOT NULL,
            categorie VARCHAR2(50 CHAR),
            uploaded_by NUMBER(19,0),
            date_upload TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_document_client PRIMARY KEY (id_doc)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 0.3 Table soutra_notification_preference
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_notification_preference (
            id_pref NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            push_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            sms_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            email_actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_notif_pref PRIMARY KEY (id_pref),
            CONSTRAINT uk_soutra_notif_pref_client UNIQUE (id_client)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 0.4 Colonnes de lecture notification, si absentes
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE soutra_notification ADD lu NUMBER(1,0) DEFAULT 0 NOT NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE soutra_notification ADD lue_le TIMESTAMP';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- 1. Index ix_soutra_beneficiaire_client
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE INDEX ix_soutra_beneficiaire_client
            ON soutra_beneficiaire (id_client)
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -942) THEN RAISE; END IF;
END;
/

-- 2. Index idx_doc_client
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE INDEX idx_doc_client
            ON soutra_document_client (id_client)
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -942) THEN RAISE; END IF;
END;
/

-- 3. Index idx_doc_date
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE INDEX idx_doc_date
            ON soutra_document_client (date_upload)
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -942) THEN RAISE; END IF;
END;
/
