BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE chequier (
            id_chequier NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            numero_chequier VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            id_compte NUMBER(19,0) NOT NULL,
            nombre_cheques NUMBER(10,0),
            premier_numero VARCHAR2(30 CHAR),
            dernier_numero VARCHAR2(30 CHAR),
            statut VARCHAR2(20 CHAR) DEFAULT ''COMMANDE'' NOT NULL,
            date_commande TIMESTAMP,
            date_remise TIMESTAMP,
            motif_opposition VARCHAR2(255 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_chequier_compte FOREIGN KEY (id_compte) REFERENCES compte(id_compte)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE remise_cheque (
            id_remise_cheque NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_chequier NUMBER(19,0) NOT NULL,
            numero_cheque VARCHAR2(30 CHAR),
            montant NUMBER(19,2),
            tireur VARCHAR2(150 CHAR),
            date_remise TIMESTAMP,
            date_valeur DATE,
            id_compte_remise NUMBER(19,0) NOT NULL,
            statut VARCHAR2(20 CHAR) DEFAULT ''REMIS'' NOT NULL,
            reference_transaction VARCHAR2(100 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_remise_cheque_chequier FOREIGN KEY (id_chequier) REFERENCES chequier(id_chequier),
            CONSTRAINT fk_remise_compte FOREIGN KEY (id_compte_remise) REFERENCES compte(id_compte)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
