BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE consultation_bic (
            id_consultation NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_client VARCHAR2(50 CHAR),
            numero_piece VARCHAR2(50 CHAR),
            encours_total NUMBER(19,2) DEFAULT 0,
            encours_sain NUMBER(19,2) DEFAULT 0,
            encours_impaye NUMBER(19,2) DEFAULT 0,
            nombre_creances NUMBER(5,0) DEFAULT 0,
            statut_bic VARCHAR2(20 CHAR),
            date_consultation DATE NOT NULL,
            client_id NUMBER(19,0),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_consultation_bic_client FOREIGN KEY (client_id) REFERENCES client(id_client)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_consultation_bic_client ON consultation_bic(client_id)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_consultation_bic_date ON consultation_bic(date_consultation)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
