-- V19__create_client_blacklist.sql
-- Migration pour la gestion de la blacklist client

-- 1. Table soutra_client_blacklist
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_client_blacklist (
            id_blacklist NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            motif VARCHAR2(50 CHAR) NOT NULL,
            details VARCHAR2(500 CHAR) NOT NULL,
            date_blacklist TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            blackliste_par VARCHAR2(120 CHAR) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_client_blacklist PRIMARY KEY (id_blacklist),
            CONSTRAINT uq_soutra_client_blacklist UNIQUE (id_client),
            CONSTRAINT fk_blacklist_client FOREIGN KEY (id_client) REFERENCES soutra_client(id_client) ON DELETE CASCADE
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. Table soutra_client_blacklist_history
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE soutra_client_blacklist_history (
            id_history NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            action VARCHAR2(30 CHAR) NOT NULL,
            client_nom VARCHAR2(100 CHAR) NOT NULL,
            client_prenom VARCHAR2(100 CHAR) NOT NULL,
            numero_client VARCHAR2(50 CHAR) NOT NULL,
            motif VARCHAR2(50 CHAR),
            details VARCHAR2(500 CHAR),
            date_action TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            operateur VARCHAR2(120 CHAR) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_soutra_blacklist_history PRIMARY KEY (id_history)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
