BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE tarification_parametre (
            id_parametre NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            cle_parametre VARCHAR2(100 CHAR) NOT NULL,
            valeur_parametre VARCHAR2(100 CHAR) NOT NULL,
            description_parametre VARCHAR2(255 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT pk_tarification_parametre PRIMARY KEY (id_parametre),
            CONSTRAINT uk_tarification_parametre_cle UNIQUE (cle_parametre)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- Oracle can raise a PK violation with INSERT ALL on identity-backed tables.
-- MERGE keeps the seed data idempotent and inserts one row at a time.
MERGE INTO tarification_parametre cible
USING (
    SELECT 'AGIO_FRAIS_TENUE_MENSUEL' AS cle_parametre,
           '1000.00' AS valeur_parametre,
           'Montant fixe des frais de tenue de compte mensuels' AS description_parametre
    FROM dual
    UNION ALL
    SELECT 'AGIO_TAUX_PENALITE_DECOUVERT',
           '0.05',
           'Taux applique au solde negatif pour la penalite de decouvert'
    FROM dual
    UNION ALL
    SELECT 'TRANSACTION_FEE_RATE_RETRAIT',
           '0.01',
           'Taux de frais applique sur un retrait'
    FROM dual
    UNION ALL
    SELECT 'TRANSACTION_FEE_RATE_VIREMENT',
           '0.015',
           'Taux de frais applique sur un virement'
    FROM dual
) source
ON (cible.cle_parametre = source.cle_parametre)
WHEN NOT MATCHED THEN
    INSERT (cle_parametre, valeur_parametre, description_parametre, created_at, updated_at)
    VALUES (
        source.cle_parametre,
        source.valeur_parametre,
        source.description_parametre,
        SYSTIMESTAMP,
        SYSTIMESTAMP
    );
