BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE liste_sanctions (
            id_sanction NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nom_complet VARCHAR2(200 CHAR) NOT NULL,
            type_personne VARCHAR2(20 CHAR) NOT NULL,
            nationalite VARCHAR2(100 CHAR),
            date_naissance DATE,
            lieu_naissance VARCHAR2(200 CHAR),
            type_sanction VARCHAR2(50 CHAR),
            reference_officielle VARCHAR2(100 CHAR),
            date_inscription DATE NOT NULL,
            actif NUMBER(1,0) DEFAULT 1,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_sanctions_nom ON liste_sanctions(nom_complet)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_sanctions_type ON liste_sanctions(type_sanction)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE liste_pep (
            id_pep NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nom_complet VARCHAR2(200 CHAR) NOT NULL,
            fonction VARCHAR2(200 CHAR),
            pays VARCHAR2(100 CHAR),
            niveau_risque VARCHAR2(20 CHAR),
            date_debut_mandat DATE,
            date_fin_mandat DATE,
            actif NUMBER(1,0) DEFAULT 1,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_pep_nom ON liste_pep(nom_complet)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
