BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE taux_fiscal (
            id_taux NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_taxe VARCHAR2(20 CHAR) NOT NULL,
            libelle VARCHAR2(200 CHAR) NOT NULL,
            taux NUMBER(7,4) NOT NULL,
            type_operation VARCHAR2(50 CHAR),
            seuil_applicable NUMBER(19,2),
            date_effet DATE NOT NULL,
            actif NUMBER(1,0) DEFAULT 1,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE declaration_fiscale (
            id_declaration NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_declaration VARCHAR2(60 CHAR) NOT NULL UNIQUE,
            type_declaration VARCHAR2(30 CHAR) NOT NULL,
            periode_debut DATE NOT NULL,
            periode_fin DATE NOT NULL,
            montant_base NUMBER(19,2) DEFAULT 0,
            montant_taxe NUMBER(19,2) DEFAULT 0,
            statut VARCHAR2(30 CHAR) DEFAULT ''BROUILLON'' NOT NULL,
            date_declaration DATE,
            agence_id NUMBER(19,0),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_declaration_agence FOREIGN KEY (agence_id) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
