BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE consentement_open_banking (
            id_consentement NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ref_consentement VARCHAR2(60 CHAR) NOT NULL UNIQUE,
            id_partenaire_api NUMBER(19,0) NOT NULL,
            client_id NUMBER(19,0) NOT NULL,
            type_consentement VARCHAR2(20 CHAR) NOT NULL,
            scope VARCHAR2(200 CHAR),
            date_debut TIMESTAMP NOT NULL,
            date_fin TIMESTAMP,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            access_token_hash VARCHAR2(255 CHAR),
            refresh_token_hash VARCHAR2(255 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_consentement_partenaire FOREIGN KEY (id_partenaire_api) REFERENCES partenaire_api(id_partenaire_api)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE consentement_history (
            id_history NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_consentement NUMBER(19,0) NOT NULL,
            ancien_statut VARCHAR2(30 CHAR),
            nouveau_statut VARCHAR2(30 CHAR) NOT NULL,
            modifie_par VARCHAR2(100 CHAR),
            motif VARCHAR2(255 CHAR),
            date_modification TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
