BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE loan_facility (
        id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_id NUMBER(19,0) NOT NULL,
        product_id NUMBER(19,0),
        principal_amount NUMBER(19,2) NOT NULL,
        outstanding_balance NUMBER(19,2) NOT NULL,
        interest_rate NUMBER(5,4) NOT NULL,
        term_months NUMBER(10,0) NOT NULL,
        start_date DATE,
        end_date DATE,
        status VARCHAR2(255 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE collateral (
        id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        loan_facility_id NUMBER(19,0) NOT NULL,
        collateral_type VARCHAR2(255 CHAR) NOT NULL,
        description VARCHAR2(255 CHAR),
        value NUMBER(19,2) NOT NULL,
        lien_status VARCHAR2(255 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE guarantor (
        id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        loan_facility_id NUMBER(19,0) NOT NULL,
        guarantor_customer_id NUMBER(19,0) NOT NULL,
        guarantee_amount NUMBER(19,2) NOT NULL,
        guarantee_percentage NUMBER(5,4),
        status VARCHAR2(255 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE beneficiary (
        id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        loan_facility_id NUMBER(19,0) NOT NULL,
        beneficiary_account VARCHAR2(255 CHAR) NOT NULL,
        beneficiary_name VARCHAR2(255 CHAR) NOT NULL,
        share_ratio NUMBER(5,4)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_collateral_loan_facility_id ON collateral(loan_facility_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_guarantor_loan_facility_id ON guarantor(loan_facility_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_beneficiary_loan_facility_id ON beneficiary(loan_facility_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
