BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE agent (
        id_agent NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        adresse VARCHAR2(255 CHAR),
        code_agent VARCHAR2(40 CHAR) NOT NULL,
        date_agrement DATE,
        date_resiliation DATE,
        nom_agent VARCHAR2(150 CHAR) NOT NULL,
        statut VARCHAR2(20 CHAR) NOT NULL,
        telephone VARCHAR2(30 CHAR),
        type_agent VARCHAR2(20 CHAR) NOT NULL,
        id_agence_rattachement NUMBER(19,0)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE type_agio (
        id_type_agio NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        code_type_agio VARCHAR2(50 CHAR) NOT NULL,
        libelle VARCHAR2(100 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE type_canal (
        id_canal NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        code_canal VARCHAR2(50 CHAR) NOT NULL,
        libelle VARCHAR2(100 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE type_compte (
        id_type_compte NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        libelle VARCHAR2(100 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE type_transaction (
        id_type_transaction NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        code_type_transaction VARCHAR2(50 CHAR) NOT NULL,
        libelle VARCHAR2(100 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE statut_client (
        id_statut_client NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_statut TIMESTAMP(6) NOT NULL,
        libelle_statut VARCHAR2(100 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE statut_envoi (
        id_statut_envoi NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        code_statut_envoi VARCHAR2(50 CHAR) NOT NULL,
        libelle VARCHAR2(100 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE role_utilisateur (
        id_role NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        code_role_utilisateur VARCHAR2(50 CHAR) NOT NULL,
        intitule_role VARCHAR2(100 CHAR) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE critere_scoring (
        id_critere_scoring NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        actif NUMBER(1,0) NOT NULL,
        categorie VARCHAR2(20 CHAR),
        code_critere VARCHAR2(40 CHAR) NOT NULL,
        libelle VARCHAR2(150 CHAR),
        poids NUMBER(5,2),
        type_valeur VARCHAR2(20 CHAR)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE grille_scoring (
        id_grille_scoring NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        actif NUMBER(1,0) NOT NULL,
        code_grille VARCHAR2(40 CHAR) NOT NULL,
        libelle VARCHAR2(150 CHAR),
        seuil_approbation NUMBER(10,0),
        seuil_rejet NUMBER(10,0)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE client (
        id_client NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        adresse VARCHAR2(255 CHAR),
        code_client VARCHAR2(50 CHAR) NOT NULL,
        commentaire_kyc VARCHAR2(500 CHAR),
        date_expiration_piece_identite DATE,
        date_inscription DATE NOT NULL,
        date_naissance DATE,
        date_soumission_kyc DATE,
        date_validation_kyc DATE,
        email VARCHAR2(150 CHAR),
        employeur VARCHAR2(150 CHAR),
        justificatif_domicile_url VARCHAR2(255 CHAR),
        justificatif_revenus_url VARCHAR2(255 CHAR),
        niveau_risque VARCHAR2(20 CHAR) NOT NULL,
        nom VARCHAR2(100 CHAR) NOT NULL,
        numero_piece_identite VARCHAR2(80 CHAR),
        pays_nationalite VARCHAR2(80 CHAR),
        pays_residence VARCHAR2(80 CHAR),
        pep NUMBER(1,0) NOT NULL,
        photo_identite_url VARCHAR2(255 CHAR),
        prenom VARCHAR2(100 CHAR) NOT NULL,
        profession VARCHAR2(120 CHAR),
        statut_kyc VARCHAR2(30 CHAR) NOT NULL,
        telephone VARCHAR2(30 CHAR),
        type_piece_identite VARCHAR2(30 CHAR),
        validateur_kyc VARCHAR2(120 CHAR),
        id_agence NUMBER(19,0),
        id_statut_client NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE utilisateur (
        id_user NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        actif NUMBER(1,0) NOT NULL,
        compte_expire_le TIMESTAMP(6),
        compte_verrouille_jusqu_au TIMESTAMP(6),
        dernier_echec_connexion TIMESTAMP(6),
        derniere_connexion_reussie TIMESTAMP(6),
        identifiants_expirent_le TIMESTAMP(6) NOT NULL,
        login VARCHAR2(100 CHAR) NOT NULL,
        mot_de_passe_modifie_le TIMESTAMP(6) NOT NULL,
        nombre_echecs_connexion NUMBER(10,0) NOT NULL,
        otp_challenge_id VARCHAR2(80 CHAR),
        otp_expire_le TIMESTAMP(6),
        otp_hash VARCHAR2(255 CHAR),
        otp_tentatives_restantes NUMBER(10,0) NOT NULL,
        password VARCHAR2(255 CHAR) NOT NULL,
        second_facteur_active NUMBER(1,0) NOT NULL,
        id_agence_active NUMBER(19,0),
        id_client NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE compte (
        id_compte NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_ouverture DATE NOT NULL,
        decouvert_autorise NUMBER(19,2),
        devise VARCHAR2(10 CHAR) NOT NULL,
        num_compte VARCHAR2(50 CHAR) NOT NULL,
        solde NUMBER(19,2) NOT NULL,
        taux_interet NUMBER(7,4),
        id_agence NUMBER(19,0),
        id_client NUMBER(19,0) NOT NULL,
        id_type_compte NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE statut_compte (
        id_statut_compte NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_statut TIMESTAMP(6) NOT NULL,
        libelle_statut VARCHAR2(100 CHAR) NOT NULL,
        id_compte NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE agio (
        id_agio NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_calcul DATE NOT NULL,
        est_preleve NUMBER(1,0) NOT NULL,
        montant NUMBER(19,2) NOT NULL,
        id_compte NUMBER(19,0) NOT NULL,
        id_type_agio NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE bank_transaction (
        id_transaction NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        code_operation_metier VARCHAR2(40 CHAR),
        date_execution TIMESTAMP(6),
        date_heure_transaction TIMESTAMP(6) NOT NULL,
        date_validation TIMESTAMP(6),
        frais NUMBER(19,2) NOT NULL,
        montant_global NUMBER(19,2) NOT NULL,
        motif_rejet VARCHAR2(500 CHAR),
        reference_unique VARCHAR2(80 CHAR) NOT NULL,
        statut_operation VARCHAR2(30 CHAR) NOT NULL,
        validation_superviseur_requise NUMBER(1,0) NOT NULL,
        id_agence_operation NUMBER(19,0),
        id_compte_destination NUMBER(19,0),
        id_compte_source NUMBER(19,0),
        id_session_caisse NUMBER(19,0),
        id_type_transaction NUMBER(19,0) NOT NULL,
        id_user NUMBER(19,0) NOT NULL,
        id_user_validation NUMBER(19,0)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE ligne_ecriture (
        id_ligne NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        montant NUMBER(19,2) NOT NULL,
        sens VARCHAR2(20 CHAR) NOT NULL,
        id_compte NUMBER(19,0) NOT NULL,
        id_transaction NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE journal_entry (
        id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        amount NUMBER(19,2) NOT NULL,
        credit_account_id NUMBER(19,0),
        debit_account_id NUMBER(19,0),
        description VARCHAR2(255 CHAR),
        entry_date TIMESTAMP(6)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE notification (
        id_notif NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_envoi DATE,
        erreur_envoi VARCHAR2(500 CHAR),
        message VARCHAR2(500 CHAR) NOT NULL,
        id_client NUMBER(19,0) NOT NULL,
        id_statut_envoi NUMBER(19,0) NOT NULL,
        id_canal NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE transaction_agent (
        id_transaction_agent NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        commission_agent NUMBER(19,2),
        date_transaction TIMESTAMP(6),
        frais NUMBER(19,2),
        montant NUMBER(19,2),
        reference_transaction VARCHAR2(100 CHAR),
        statut VARCHAR2(20 CHAR) NOT NULL,
        type_operation VARCHAR2(30 CHAR) NOT NULL,
        id_agent NUMBER(19,0) NOT NULL,
        id_client NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE commission_agent (
        id_commission_agent NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_calcul TIMESTAMP(6),
        date_paiement TIMESTAMP(6),
        montant_commission NUMBER(19,2),
        statut VARCHAR2(20 CHAR) NOT NULL,
        type_commission VARCHAR2(20 CHAR) NOT NULL,
        id_agent NUMBER(19,0) NOT NULL,
        id_transaction_agent NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE portefeuille_agent (
        id_portefeuille_agent NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        devise VARCHAR2(10 CHAR) NOT NULL,
        plafond_maximum NUMBER(19,2),
        plafond_minimum NUMBER(19,2),
        solde NUMBER(19,2),
        statut VARCHAR2(20 CHAR) NOT NULL,
        id_agent NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE tontine (
        id_tontine NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        code_tontine VARCHAR2(40 CHAR) NOT NULL,
        date_debut DATE,
        date_fin DATE,
        intitule VARCHAR2(150 CHAR) NOT NULL,
        montant_cotisation NUMBER(19,2),
        nombre_participants NUMBER(10,0),
        periodicite VARCHAR2(20 CHAR),
        statut VARCHAR2(20 CHAR) NOT NULL,
        type_tontine VARCHAR2(20 CHAR) NOT NULL,
        id_agence NUMBER(19,0)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE tour_tontine (
        id_tour_tontine NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_tour DATE,
        montant_collecte NUMBER(19,2),
        numero_tour NUMBER(10,0) NOT NULL,
        statut VARCHAR2(20 CHAR) NOT NULL,
        id_beneficiaire NUMBER(19,0) NOT NULL,
        id_tontine NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE cotisation_tontine (
        id_cotisation_tontine NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        date_cotisation DATE,
        montant_cotise NUMBER(19,2),
        reference_transaction VARCHAR2(100 CHAR),
        statut VARCHAR2(20 CHAR) NOT NULL,
        id_participant NUMBER(19,0) NOT NULL,
        id_tour_tontine NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE grille_scoring_detail (
        id_grille_scoring_detail NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        points NUMBER(10,0) NOT NULL,
        valeur_max VARCHAR2(100 CHAR),
        valeur_min VARCHAR2(100 CHAR),
        id_critere_scoring NUMBER(19,0) NOT NULL,
        id_grille_scoring NUMBER(19,0) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE resultat_scoring (
        id_resultat_scoring NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP(6) NOT NULL,
        updated_at TIMESTAMP(6) NOT NULL,
        id_demande_credit NUMBER(19,0) NOT NULL,
        id_grille_scoring NUMBER(19,0) NOT NULL,
        score_total NUMBER(10,0),
        decision VARCHAR2(20 CHAR),
        details CLOB,
        date_scoring TIMESTAMP(6)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
