BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE billetage_caisse (
            id_billetage NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_session_caisse NUMBER(19,0) NOT NULL,
            coupure NUMBER(19,2) NOT NULL,
            quantite NUMBER(10,0) NOT NULL,
            total NUMBER(19,2) NOT NULL,
            type_billetage VARCHAR2(20 CHAR) DEFAULT ''BILLET'' NOT NULL,
            date_billetage TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_billetage_session_caisse FOREIGN KEY (id_session_caisse)
                REFERENCES session_caisse(id_session_caisse)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_billetage_session_caisse ON billetage_caisse(id_session_caisse)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE journal_appel_externe (
            id_journal_appel NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_partenaire_api NUMBER(19,0),
            code_partenaire VARCHAR2(40 CHAR) NOT NULL,
            endpoint VARCHAR2(255 CHAR) NOT NULL,
            methode VARCHAR2(10 CHAR) NOT NULL,
            statut VARCHAR2(20 CHAR) NOT NULL,
            code_statut_http NUMBER(10,0),
            request_body CLOB,
            response_body CLOB,
            ip_source VARCHAR2(45 CHAR),
            date_appel TIMESTAMP NOT NULL,
            duree_ms NUMBER(19,0),
            id_utilisateur NUMBER(19,0),
            erreur_message CLOB,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_journal_appel_partenaire FOREIGN KEY (id_partenaire_api)
                REFERENCES partenaire_api(id_partenaire_api)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_journal_appel_partenaire ON journal_appel_externe(id_partenaire_api)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_journal_appel_date ON journal_appel_externe(date_appel)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
