BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE region (
            id_region NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_region VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            nom_region VARCHAR2(120 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIVE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE agence (
            id_agence NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_agence VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            nom_agence VARCHAR2(150 CHAR) NOT NULL,
            adresse VARCHAR2(255 CHAR),
            telephone VARCHAR2(30 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIVE'' NOT NULL,
            id_region NUMBER(19,0),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_agence_region FOREIGN KEY (id_region) REFERENCES region(id_region)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE guichet (
            id_guichet NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_guichet VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            nom_guichet VARCHAR2(120 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            id_agence NUMBER(19,0) NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_guichet_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE affectation_utilisateur_agence (
            id_affectation NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_user NUMBER(19,0) NOT NULL,
            id_agence NUMBER(19,0) NOT NULL,
            role_operatoire VARCHAR2(80 CHAR),
            date_debut DATE NOT NULL,
            date_fin DATE,
            actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_affectation_user FOREIGN KEY (id_user) REFERENCES utilisateur(id_user),
            CONSTRAINT fk_affectation_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE produit_credit (
            id_produit_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_produit VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            categorie VARCHAR2(80 CHAR) NOT NULL,
            taux_annuel NUMBER(9,4) NOT NULL,
            duree_min_mois NUMBER(10,0) NOT NULL,
            duree_max_mois NUMBER(10,0) NOT NULL,
            montant_min NUMBER(19,2) NOT NULL,
            montant_max NUMBER(19,2) NOT NULL,
            frais_dossier NUMBER(19,2) DEFAULT 0 NOT NULL,
            assurance_taux NUMBER(9,4) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE demande_credit (
            id_demande_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_dossier VARCHAR2(60 CHAR) NOT NULL UNIQUE,
            id_client NUMBER(19,0) NOT NULL,
            id_produit_credit NUMBER(19,0) NOT NULL,
            id_agence NUMBER(19,0),
            montant_demande NUMBER(19,2) NOT NULL,
            duree_mois NUMBER(10,0) NOT NULL,
            objet_credit VARCHAR2(255 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''BROUILLON'' NOT NULL,
            score_credit NUMBER(10,0),
            avis_comite VARCHAR2(500 CHAR),
            decision_finale VARCHAR2(500 CHAR),
            date_decision TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_demande_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_demande_produit_credit FOREIGN KEY (id_produit_credit) REFERENCES produit_credit(id_produit_credit),
            CONSTRAINT fk_demande_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE credit (
            id_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_credit VARCHAR2(60 CHAR) NOT NULL UNIQUE,
            id_demande_credit NUMBER(19,0) NOT NULL,
            id_client NUMBER(19,0) NOT NULL,
            montant_accorde NUMBER(19,2) NOT NULL,
            taux_annuel NUMBER(9,4) NOT NULL,
            duree_mois NUMBER(10,0) NOT NULL,
            mensualite NUMBER(19,2),
            capital_restant_du NUMBER(19,2) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            date_deblocage TIMESTAMP,
            date_prochaine_echeance DATE,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_credit_demande FOREIGN KEY (id_demande_credit) REFERENCES demande_credit(id_demande_credit),
            CONSTRAINT fk_credit_client FOREIGN KEY (id_client) REFERENCES client(id_client)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE produit_epargne (
            id_produit_epargne NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_produit VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            categorie VARCHAR2(80 CHAR) NOT NULL,
            taux_interet NUMBER(9,4) DEFAULT 0 NOT NULL,
            depot_initial_min NUMBER(19,2) DEFAULT 0 NOT NULL,
            solde_minimum NUMBER(19,2) DEFAULT 0 NOT NULL,
            frequence_interet VARCHAR2(40 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE depot_a_terme (
            id_depot_terme NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_depot VARCHAR2(60 CHAR) NOT NULL UNIQUE,
            id_client NUMBER(19,0) NOT NULL,
            id_produit_epargne NUMBER(19,0) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            duree_mois NUMBER(10,0) NOT NULL,
            taux_applique NUMBER(9,4) NOT NULL,
            interets_estimes NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            date_souscription DATE NOT NULL,
            date_echeance DATE NOT NULL,
            renouvellement_auto NUMBER(1,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_depot_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_depot_produit FOREIGN KEY (id_produit_epargne) REFERENCES produit_epargne(id_produit_epargne)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE caisse (
            id_caisse NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_caisse VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(120 CHAR) NOT NULL,
            id_agence NUMBER(19,0) NOT NULL,
            id_guichet NUMBER(19,0),
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIVE'' NOT NULL,
            solde_theorique NUMBER(19,2) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_caisse_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence),
            CONSTRAINT fk_caisse_guichet FOREIGN KEY (id_guichet) REFERENCES guichet(id_guichet)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE session_caisse (
            id_session_caisse NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_caisse NUMBER(19,0) NOT NULL,
            id_user NUMBER(19,0) NOT NULL,
            date_ouverture TIMESTAMP NOT NULL,
            date_fermeture TIMESTAMP,
            solde_ouverture NUMBER(19,2) NOT NULL,
            solde_theorique_fermeture NUMBER(19,2) DEFAULT 0 NOT NULL,
            solde_physique_fermeture NUMBER(19,2),
            ecart NUMBER(19,2),
            statut VARCHAR2(30 CHAR) DEFAULT ''OUVERTE'' NOT NULL,
            commentaire VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_session_caisse FOREIGN KEY (id_caisse) REFERENCES caisse(id_caisse),
            CONSTRAINT fk_session_user FOREIGN KEY (id_user) REFERENCES utilisateur(id_user)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE action_en_attente (
            id_action_en_attente NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type_action VARCHAR2(80 CHAR) NOT NULL,
            ressource VARCHAR2(80 CHAR) NOT NULL,
            reference_ressource VARCHAR2(80 CHAR),
            ancienne_valeur CLOB,
            nouvelle_valeur CLOB,
            statut VARCHAR2(30 CHAR) DEFAULT ''EN_ATTENTE'' NOT NULL,
            commentaire_maker VARCHAR2(500 CHAR),
            commentaire_checker VARCHAR2(500 CHAR),
            id_maker NUMBER(19,0) NOT NULL,
            id_checker NUMBER(19,0),
            date_validation TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_action_maker FOREIGN KEY (id_maker) REFERENCES utilisateur(id_user),
            CONSTRAINT fk_action_checker FOREIGN KEY (id_checker) REFERENCES utilisateur(id_user)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE alerte_conformite (
            id_alerte_conformite NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_alerte VARCHAR2(60 CHAR) NOT NULL UNIQUE,
            type_alerte VARCHAR2(80 CHAR) NOT NULL,
            niveau_risque VARCHAR2(30 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''OUVERTE'' NOT NULL,
            id_client NUMBER(19,0),
            id_transaction NUMBER(19,0),
            resume VARCHAR2(255 CHAR) NOT NULL,
            details CLOB,
            date_detection TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_alerte_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_alerte_transaction FOREIGN KEY (id_transaction) REFERENCES bank_transaction(id_transaction)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE employe (
            id_employe NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            matricule VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            nom_complet VARCHAR2(150 CHAR) NOT NULL,
            poste VARCHAR2(120 CHAR),
            service VARCHAR2(120 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            date_embauche DATE,
            email VARCHAR2(150 CHAR),
            telephone VARCHAR2(30 CHAR),
            id_agence NUMBER(19,0),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_employe_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE appareil_client (
            id_appareil_client NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_client NUMBER(19,0) NOT NULL,
            empreinte_appareil VARCHAR2(120 CHAR) NOT NULL UNIQUE,
            plateforme VARCHAR2(40 CHAR) NOT NULL,
            nom_appareil VARCHAR2(120 CHAR),
            autorise NUMBER(1,0) DEFAULT 1 NOT NULL,
            derniere_connexion TIMESTAMP,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_appareil_client FOREIGN KEY (id_client) REFERENCES client(id_client)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE partenaire_api (
            id_partenaire_api NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_partenaire VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            nom_partenaire VARCHAR2(150 CHAR) NOT NULL,
            type_partenaire VARCHAR2(80 CHAR) NOT NULL,
            webhook_url VARCHAR2(255 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            oauth_client_id VARCHAR2(120 CHAR),
            cle_api VARCHAR2(255 CHAR),
            quotas_journaliers NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE rapport_reglementaire (
            id_rapport_reglementaire NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_rapport VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            type_rapport VARCHAR2(80 CHAR) NOT NULL,
            periode VARCHAR2(30 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''BROUILLON'' NOT NULL,
            chemin_fichier VARCHAR2(255 CHAR),
            date_generation TIMESTAMP,
            commentaire VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'CLIENT' AND column_name = 'ID_AGENCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE client ADD (id_agence NUMBER(19,0) NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM user_constraints WHERE table_name = 'CLIENT' AND constraint_name = 'FK_CLIENT_AGENCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE client ADD CONSTRAINT fk_client_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)';
    END IF;
END;
/

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'COMPTE' AND column_name = 'ID_AGENCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE compte ADD (id_agence NUMBER(19,0) NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM user_constraints WHERE table_name = 'COMPTE' AND constraint_name = 'FK_COMPTE_AGENCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE compte ADD CONSTRAINT fk_compte_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)';
    END IF;
END;
/

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'UTILISATEUR' AND column_name = 'ID_AGENCE_ACTIVE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE utilisateur ADD (id_agence_active NUMBER(19,0) NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM user_constraints WHERE table_name = 'UTILISATEUR' AND constraint_name = 'FK_USER_AGENCE_ACTIVE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE utilisateur ADD CONSTRAINT fk_user_agence_active FOREIGN KEY (id_agence_active) REFERENCES agence(id_agence)';
    END IF;
END;
/

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'BANK_TRANSACTION' AND column_name = 'ID_AGENCE_OPERATION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE bank_transaction ADD (id_agence_operation NUMBER(19,0) NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM user_constraints WHERE table_name = 'BANK_TRANSACTION' AND constraint_name = 'FK_TX_AGENCE_OPERATION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE bank_transaction ADD CONSTRAINT fk_tx_agence_operation FOREIGN KEY (id_agence_operation) REFERENCES agence(id_agence)';
    END IF;
END;
/
