BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE echeance_credit (
            id_echeance_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_credit NUMBER(19,0) NOT NULL,
            numero_echeance NUMBER(10,0) NOT NULL,
            date_echeance DATE NOT NULL,
            capital_prevu NUMBER(19,2) NOT NULL,
            interet_prevu NUMBER(19,2) NOT NULL,
            assurance_prevue NUMBER(19,2) DEFAULT 0 NOT NULL,
            total_prevu NUMBER(19,2) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''A_ECHOIR'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_echeance_credit FOREIGN KEY (id_credit) REFERENCES credit(id_credit)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'CREDIT' AND column_name = 'REFERENCE_TRANSACTION_DEBLOCAGE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE credit ADD (reference_transaction_deblocage VARCHAR2(80 CHAR) NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'CREDIT' AND column_name = 'FRAIS_PRELEVES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE credit ADD (frais_preleves NUMBER(19,2) DEFAULT 0 NOT NULL)';
    END IF;
END;
/

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'DEPOT_A_TERME' AND column_name = 'ID_COMPTE_SUPPORT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE depot_a_terme ADD (id_compte_support NUMBER(19,0) NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM user_tab_cols WHERE table_name = 'DEPOT_A_TERME' AND column_name = 'REFERENCE_TRANSACTION_SOUSCRIPTION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE depot_a_terme ADD (reference_transaction_souscription VARCHAR2(80 CHAR) NULL)';
    END IF;
END;
/
