-- V7: SYSCOHADA-SFD Chart of Accounts for Microfinance
-- Classes 1-7 financial accounts per BCEAO/UEMOA regulations

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE compte_comptable (
            numero_compte VARCHAR2(20) NOT NULL,
            intitule VARCHAR2(150) NOT NULL,
            classe VARCHAR2(20) NOT NULL,
            nature_solde VARCHAR2(10) NOT NULL,
            solde NUMBER(19, 2) DEFAULT 0.00 NOT NULL,
            actif_sn CHAR(1) DEFAULT 'Y' NOT NULL,
            CONSTRAINT pk_compte_comptable PRIMARY KEY (numero_compte),
            CONSTRAINT ck_compte_comptable_nature_solde CHECK (nature_solde IN ('DEBITEUR', 'CREDITEUR')),
            CONSTRAINT ck_compte_comptable_actif_sn CHECK (actif_sn IN ('Y', 'N'))
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE transaction_comptable (
            id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            date_transaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            libelle VARCHAR2(255) NOT NULL,
            reference_operateur VARCHAR2(50),
            CONSTRAINT pk_transaction_comptable PRIMARY KEY (id)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE ecriture_comptable (
            id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            transaction_id NUMBER(19, 0) NOT NULL,
            numero_compte VARCHAR2(20) NOT NULL,
            debit NUMBER(19, 2) DEFAULT 0.00 NOT NULL,
            credit NUMBER(19, 2) DEFAULT 0.00 NOT NULL,
            CONSTRAINT pk_ecriture_comptable PRIMARY KEY (id),
            CONSTRAINT fk_ecriture_tx FOREIGN KEY (transaction_id) REFERENCES transaction_comptable(id),
            CONSTRAINT fk_ecriture_compte FOREIGN KEY (numero_compte) REFERENCES compte_comptable(numero_compte),
            CONSTRAINT ck_ecriture_solde CHECK ((debit > 0 AND credit = 0) OR (debit = 0 AND credit > 0))
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_ecriture_compte ON ecriture_comptable(numero_compte)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_ecriture_tx ON ecriture_comptable(transaction_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- Seed: SYSCOHADA-SFD Chart of Accounts
MERGE INTO compte_comptable cible
USING (
    SELECT '15110000' AS numero_compte, 'Caisse Principale Agence' AS intitule, 'CLASSE_1' AS classe, 'DEBITEUR' AS nature_solde, 15000000.00 AS solde, 'Y' AS actif_sn FROM dual
    UNION ALL
    SELECT '16110001', 'Banque Partenaire - Ecobank Cote d''Ivoire', 'CLASSE_1', 'DEBITEUR', 50000000.00, 'Y' FROM dual
    UNION ALL
    SELECT '20110000', 'Encours Credits Court Terme Clientele', 'CLASSE_2', 'DEBITEUR', 0.00, 'Y' FROM dual
    UNION ALL
    SELECT '25110000', 'Depots d''Epargne a Vue Collectes (Clients)', 'CLASSE_2', 'CREDITEUR', 0.00, 'Y' FROM dual
    UNION ALL
    SELECT '25210000', 'Depots d''Epargne a Terme (DAT / Comptes Bloques)', 'CLASSE_2', 'CREDITEUR', 0.00, 'Y' FROM dual
    UNION ALL
    SELECT '50110000', 'Capital Social / Fonds Associatif SFD', 'CLASSE_5', 'CREDITEUR', 65000000.00, 'Y' FROM dual
    UNION ALL
    SELECT '70110000', 'Interets percus sur credits (Produits)', 'CLASSE_7', 'CREDITEUR', 0.00, 'Y' FROM dual
    UNION ALL
    SELECT '70510000', 'Commissions et Frais de dossier percus', 'CLASSE_7', 'CREDITEUR', 0.00, 'Y' FROM dual
) source
ON (cible.numero_compte = source.numero_compte)
WHEN NOT MATCHED THEN
    INSERT (numero_compte, intitule, classe, nature_solde, solde, actif_sn)
    VALUES (source.numero_compte, source.intitule, source.classe, source.nature_solde, source.solde, source.actif_sn);
