BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE classe_comptable (
            id_classe_comptable NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_classe VARCHAR2(10 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(120 CHAR) NOT NULL,
            ordre_affichage NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE compte_comptable (
            id_compte_comptable NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            numero_compte VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            intitule VARCHAR2(150 CHAR) NOT NULL,
            type_solde VARCHAR2(20 CHAR) DEFAULT ''MIXTE'' NOT NULL,
            compte_interne NUMBER(1,0) DEFAULT 0 NOT NULL,
            id_classe_comptable NUMBER(19,0),
            id_agence NUMBER(19,0),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_compte_comptable_classe FOREIGN KEY (id_classe_comptable) REFERENCES classe_comptable(id_classe_comptable),
            CONSTRAINT fk_compte_comptable_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE journal_comptable (
            id_journal_comptable NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_journal VARCHAR2(20 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(120 CHAR) NOT NULL,
            type_journal VARCHAR2(40 CHAR) NOT NULL,
            actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE schema_comptable (
            id_schema_comptable NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_operation VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            compte_debit VARCHAR2(30 CHAR) NOT NULL,
            compte_credit VARCHAR2(30 CHAR) NOT NULL,
            compte_frais VARCHAR2(30 CHAR),
            journal_code VARCHAR2(20 CHAR),
            actif NUMBER(1,0) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ecriture_comptable (
            id_ecriture_comptable NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_piece VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            id_journal_comptable NUMBER(19,0) NOT NULL,
            date_comptable DATE NOT NULL,
            date_valeur DATE,
            libelle VARCHAR2(255 CHAR) NOT NULL,
            source_type VARCHAR2(40 CHAR),
            source_reference VARCHAR2(80 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''COMPTABILISEE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_ecriture_journal FOREIGN KEY (id_journal_comptable) REFERENCES journal_comptable(id_journal_comptable)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ligne_ecriture_comptable (
            id_ligne_ecriture_comptable NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_ecriture_comptable NUMBER(19,0) NOT NULL,
            id_compte_comptable NUMBER(19,0) NOT NULL,
            sens VARCHAR2(20 CHAR) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            reference_auxiliaire VARCHAR2(80 CHAR),
            libelle_auxiliaire VARCHAR2(150 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_ligne_ecriture_entete FOREIGN KEY (id_ecriture_comptable) REFERENCES ecriture_comptable(id_ecriture_comptable),
            CONSTRAINT fk_ligne_ecriture_compte FOREIGN KEY (id_compte_comptable) REFERENCES compte_comptable(id_compte_comptable)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE cloture_comptable (
            id_cloture_comptable NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type_cloture VARCHAR2(30 CHAR) NOT NULL,
            date_debut DATE NOT NULL,
            date_fin DATE NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''TERMINEE'' NOT NULL,
            commentaire VARCHAR2(500 CHAR),
            total_ecritures NUMBER(10,0) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE coffre (
            id_coffre NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_coffre VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(120 CHAR) NOT NULL,
            id_agence NUMBER(19,0) NOT NULL,
            solde_theorique NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_coffre_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE mouvement_coffre (
            id_mouvement_coffre NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_coffre NUMBER(19,0) NOT NULL,
            type_mouvement VARCHAR2(40 CHAR) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            reference_mouvement VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            commentaire VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_mouvement_coffre FOREIGN KEY (id_coffre) REFERENCES coffre(id_coffre)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE approvisionnement_caisse (
            id_approvisionnement_caisse NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_coffre NUMBER(19,0) NOT NULL,
            id_caisse NUMBER(19,0) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            reference_operation VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_appro_caisse_coffre FOREIGN KEY (id_coffre) REFERENCES coffre(id_coffre),
            CONSTRAINT fk_appro_caisse_caisse FOREIGN KEY (id_caisse) REFERENCES caisse(id_caisse)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE delestage_caisse (
            id_delestage_caisse NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_coffre NUMBER(19,0) NOT NULL,
            id_caisse NUMBER(19,0) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            reference_operation VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_delestage_caisse_coffre FOREIGN KEY (id_coffre) REFERENCES coffre(id_coffre),
            CONSTRAINT fk_delestage_caisse_caisse FOREIGN KEY (id_caisse) REFERENCES caisse(id_caisse)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE operateur_mobile_money (
            id_operateur_mobile_money NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_operateur VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            nom_operateur VARCHAR2(120 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE wallet_client (
            id_wallet_client NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_client NUMBER(19,0) NOT NULL,
            id_operateur_mobile_money NUMBER(19,0) NOT NULL,
            id_compte NUMBER(19,0) NOT NULL,
            numero_wallet VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_wallet_client FOREIGN KEY (id_client) REFERENCES client(id_client),
            CONSTRAINT fk_wallet_operateur FOREIGN KEY (id_operateur_mobile_money) REFERENCES operateur_mobile_money(id_operateur_mobile_money),
            CONSTRAINT fk_wallet_compte FOREIGN KEY (id_compte) REFERENCES compte(id_compte)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE transaction_mobile_money (
            id_transaction_mobile_money NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_transaction VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            id_wallet_client NUMBER(19,0) NOT NULL,
            type_transaction VARCHAR2(30 CHAR) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            frais NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''TERMINEE'' NOT NULL,
            reference_transaction_interne VARCHAR2(80 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_transaction_mm_wallet FOREIGN KEY (id_wallet_client) REFERENCES wallet_client(id_wallet_client)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE risque (
            id_risque NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_risque VARCHAR2(30 CHAR) NOT NULL UNIQUE,
            categorie VARCHAR2(60 CHAR) NOT NULL,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            niveau VARCHAR2(30 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''OUVERT'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE incident_operationnel (
            id_incident_operationnel NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_incident VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            id_risque NUMBER(19,0),
            type_incident VARCHAR2(60 CHAR) NOT NULL,
            gravite VARCHAR2(30 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''OUVERT'' NOT NULL,
            description VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_incident_risque FOREIGN KEY (id_risque) REFERENCES risque(id_risque)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE stress_test (
            id_stress_test NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_scenario VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            taux_defaut NUMBER(9,4) DEFAULT 0 NOT NULL,
            taux_retrait NUMBER(9,4) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE resultat_stress_test (
            id_resultat_stress_test NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_stress_test NUMBER(19,0) NOT NULL,
            encours_credit NUMBER(19,2) DEFAULT 0 NOT NULL,
            pertes_projetees NUMBER(19,2) DEFAULT 0 NOT NULL,
            retraits_projetes NUMBER(19,2) DEFAULT 0 NOT NULL,
            liquidite_nette NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut_resultat VARCHAR2(30 CHAR) DEFAULT ''STABLE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_resultat_stress_test FOREIGN KEY (id_stress_test) REFERENCES stress_test(id_stress_test)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
