BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE echeance_credit ADD (
        capital_paye NUMBER(19,2) DEFAULT 0 NOT NULL,
        interet_paye NUMBER(19,2) DEFAULT 0 NOT NULL,
        assurance_payee NUMBER(19,2) DEFAULT 0 NOT NULL,
        date_derniere_regularisation DATE
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE garantie_credit (
            id_garantie_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_credit NUMBER(19,0) NOT NULL,
            type_garantie VARCHAR2(60 CHAR) NOT NULL,
            description VARCHAR2(150 CHAR) NOT NULL,
            valeur NUMBER(19,2) NOT NULL,
            valeur_nantie NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIVE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_garantie_credit_credit FOREIGN KEY (id_credit) REFERENCES credit(id_credit)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE remboursement_credit (
            id_remboursement_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_credit NUMBER(19,0) NOT NULL,
            reference_remboursement VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            montant NUMBER(19,2) NOT NULL,
            capital_paye NUMBER(19,2) DEFAULT 0 NOT NULL,
            interet_paye NUMBER(19,2) DEFAULT 0 NOT NULL,
            assurance_payee NUMBER(19,2) DEFAULT 0 NOT NULL,
            reference_transaction VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            date_paiement TIMESTAMP NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''COMPTABILISE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_remboursement_credit_credit FOREIGN KEY (id_credit) REFERENCES credit(id_credit)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE impaye_credit (
            id_impaye_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_credit NUMBER(19,0) NOT NULL,
            id_echeance_credit NUMBER(19,0) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            jours_retard NUMBER(10,0) NOT NULL,
            classe_risque VARCHAR2(30 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''OUVERT'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_impaye_credit_credit FOREIGN KEY (id_credit) REFERENCES credit(id_credit),
            CONSTRAINT fk_impaye_credit_echeance FOREIGN KEY (id_echeance_credit) REFERENCES echeance_credit(id_echeance_credit)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE provision_credit (
            id_provision_credit NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_credit NUMBER(19,0) NOT NULL,
            date_calcul DATE NOT NULL,
            taux_provision NUMBER(9,4) DEFAULT 0 NOT NULL,
            montant_provision NUMBER(19,2) DEFAULT 0 NOT NULL,
            reference_piece_comptable VARCHAR2(80 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''CALCULEE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_provision_credit_credit FOREIGN KEY (id_credit) REFERENCES credit(id_credit)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE lot_compensation (
            id_lot_compensation NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_lot VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            type_lot VARCHAR2(40 CHAR) NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''INITIE'' NOT NULL,
            date_traitement TIMESTAMP,
            commentaire VARCHAR2(500 CHAR),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ordre_paiement_externe (
            id_ordre_paiement_externe NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_ordre VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            type_flux VARCHAR2(40 CHAR) NOT NULL,
            sens VARCHAR2(20 CHAR) NOT NULL,
            montant NUMBER(19,2) NOT NULL,
            frais NUMBER(19,2) DEFAULT 0 NOT NULL,
            id_compte NUMBER(19,0) NOT NULL,
            id_lot_compensation NUMBER(19,0),
            reference_externe VARCHAR2(80 CHAR),
            reference_transaction_interne VARCHAR2(80 CHAR),
            destination_detail VARCHAR2(150 CHAR),
            date_initiation TIMESTAMP NOT NULL,
            date_reglement TIMESTAMP,
            date_rapprochement TIMESTAMP,
            statut VARCHAR2(30 CHAR) DEFAULT ''INITIE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_ordre_paiement_lot FOREIGN KEY (id_lot_compensation) REFERENCES lot_compensation(id_lot_compensation)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
