BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE budget (
            id_budget NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_budget VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            annee NUMBER(10,0) NOT NULL,
            id_agence NUMBER(19,0),
            montant_total NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''BROUILLON'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_budget_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ligne_budget (
            id_ligne_budget NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_budget NUMBER(19,0) NOT NULL,
            rubrique VARCHAR2(100 CHAR) NOT NULL,
            montant_prevu NUMBER(19,2) DEFAULT 0 NOT NULL,
            montant_engage NUMBER(19,2) DEFAULT 0 NOT NULL,
            montant_consomme NUMBER(19,2) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_ligne_budget_budget FOREIGN KEY (id_budget) REFERENCES budget(id_budget)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE fournisseur (
            id_fournisseur NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_fournisseur VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            nom VARCHAR2(150 CHAR) NOT NULL,
            contact VARCHAR2(150 CHAR),
            telephone VARCHAR2(30 CHAR),
            email VARCHAR2(150 CHAR),
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIF'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE commande_achat (
            id_commande_achat NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_commande VARCHAR2(80 CHAR) NOT NULL UNIQUE,
            id_fournisseur NUMBER(19,0) NOT NULL,
            id_agence NUMBER(19,0),
            objet VARCHAR2(150 CHAR) NOT NULL,
            montant NUMBER(19,2) DEFAULT 0 NOT NULL,
            date_commande DATE NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''INITIEE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_commande_fournisseur FOREIGN KEY (id_fournisseur) REFERENCES fournisseur(id_fournisseur),
            CONSTRAINT fk_commande_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE bulletin_paie (
            id_bulletin_paie NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_employe NUMBER(19,0) NOT NULL,
            periode VARCHAR2(20 CHAR) NOT NULL,
            salaire_brut NUMBER(19,2) DEFAULT 0 NOT NULL,
            retenues NUMBER(19,2) DEFAULT 0 NOT NULL,
            salaire_net NUMBER(19,2) DEFAULT 0 NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''BROUILLON'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_bulletin_employe FOREIGN KEY (id_employe) REFERENCES employe(id_employe)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE immobilisation (
            id_immobilisation NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_immobilisation VARCHAR2(40 CHAR) NOT NULL UNIQUE,
            libelle VARCHAR2(150 CHAR) NOT NULL,
            id_agence NUMBER(19,0),
            valeur_origine NUMBER(19,2) DEFAULT 0 NOT NULL,
            duree_amortissement_mois NUMBER(10,0) NOT NULL,
            amortissement_mensuel NUMBER(19,2) DEFAULT 0 NOT NULL,
            valeur_nette NUMBER(19,2) DEFAULT 0 NOT NULL,
            date_acquisition DATE NOT NULL,
            statut VARCHAR2(30 CHAR) DEFAULT ''ACTIVE'' NOT NULL,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            CONSTRAINT fk_immobilisation_agence FOREIGN KEY (id_agence) REFERENCES agence(id_agence)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
