spring.application.name=core-banking
# ==========================================
# CONNEXION A LA BASE DE DONNEES ORACLE
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=core_banking_user
spring.datasource.password=core_banking_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# ==========================================
# CONFIGURATION HIBERNATE (JPA)
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
# Affiche le SQL genere dans la console pour verifier que l'UML est bien traduit
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ==========================================
# CHARGEMENT DES DONNEES DE REFERENCE
# ==========================================
# Active l'execution de data.sql a chaque demarrage (MERGE = idempotent, pas de doublons)
spring.sql.init.mode=always
# Garantit que Hibernate cree les tables AVANT que data.sql ne s'execute
spring.jpa.defer-datasource-initialization=true
# Desactive l'integration Docker Compose si Docker Desktop n'est pas lance.
spring.docker.compose.enabled=false


