spring.application.name=core-banking
# ===============================
# CONFIGURATION BASE DE DONNÉES H2
# ===============================
spring.datasource.url=jdbc:h2:mem:microfinancedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONFIGURATION HIBERNATE / JPA
# ===============================
# Dit à Hibernate de recréer les tables à chaque démarrage (idéal pour le développement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Affiche le SQL généré dans la console pour vérifier que l'UML est bien traduit
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONSOLE H2 (Interface Web)
# ===============================
# Permet d'accéder à la base de données via le navigateur
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console