spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
logging.level.com.soutra.microfinance=${APP_LOG_LEVEL:DEBUG}
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=WARN
logging.level.org.hibernate.engine.jdbc=WARN
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,flyway}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

